### ISSUE TITLE
Can't run on KitKat

### ISSUE THREAD

**Issue by 0xFF0** [theQRL/mobile-wallet#16]
Action: Start the application.
Expected Result: Application starts.
What happened: Application crash.
Android/iOS version: Android 4.4.2
Android/iOS handset model: NoxPlayer 6.2.6.1 (SM-G955N emulation)   

Error from catlog below:

![kitkat](https://user-images.githubusercontent.com/42574567/50522096-2d6d7b80-0a97-11e9-9e14-a4587aa9bfbd.png)

**Comment by ademcan** [comment]
Although the error message indicates something different, see https://github.com/theQRL/mobile-wallet/issues/18 for Android version related issues.
