### ISSUE TITLE
Display problem: Go back button

### ISSUE THREAD

**Issue by 0xFF0** [theQRL/mobile-wallet#17]
Action: On the first screen, click on "Advanced Options".
Expected Result: "Go Back" button should be visible.
What happened: "Go Back" button is white.
Android/iOS version: Android 5.1.1
Android/iOS handset model: NoxPlayer 6.2.6.1 (Nexus 6 emulation).

![goback](https://user-images.githubusercontent.com/42574567/50522244-e764e780-0a97-11e9-9adf-b5dd739360ac.png)

**Comment by ademcan** [comment]
Hi 0xFF0, thanks for your comment. This issue is now solved, the white (and invisible) button had been changed to a red Cancel button on #35
