### ISSUE TITLE
Can't create a wallet with Lollipop

### ISSUE THREAD

**Issue by 0xFF0** [theQRL/mobile-wallet#18]
Action: Create a new wallet.
What happened: App crash.
Android/iOS version: Android 5.1.1
Android/iOS handset model: NoxPlayer 6.2.6.1 (Nexus 6 emulation).

The bug might be related to the variable KEY_ALGORITHM_AES (because it was added in API level 23).

![wallet](https://user-images.githubusercontent.com/42574567/50532631-08562880-0aea-11e9-8917-3fc35a99c7eb.png)

**Comment by ademcan** [comment]
Hi 0xFF0, thank you for your comment. Indeed, the Android version requires API 23+ to work. As you mentioned, the main reason is that we are using KEY_ALGORITHM_AES for the Cipher, you can see the supported list of algorithms here https://developer.android.com/training/articles/keystore#SupportedCiphers
Using AES, we rely on KeyGenParameterSpec (https://developer.android.com/reference/android/security/keystore/KeyGenParameterSpec) class which is also only available for 23+.
I will label this issue as "On Hold" and see if it makes sense to add support for lower level APIs.

**Comment by jplomas** [comment]
No version of Lollipop is supported with security updates and will not be supported.
