### ISSUE TITLE
App crash - QR Code menu

### ISSUE THREAD

**Issue by 0xFF0** [theQRL/mobile-wallet#19]
**Action**:  In the menu, click on "Create new Wallet". Click on the QR code button. Then, click on the menu button.
**What happened**: App crash. 
**Android/iOS version**: 7.1.2
**Android/iOS handset model**: NoxPlayer 6.2.6.1 (Galaxy Note 3 emulation).

![qr code](https://user-images.githubusercontent.com/42574567/50532775-3a688a00-0aec-11e9-9e04-f29e5b7bd4ac.png)

**Comment by ademcan** [comment]
This issue is now solved in #36. I removed the sandwich icon to access the side menu. The QR code view is a modal and does not require to access main menu actions. Users can now see the QR code modal and dismiss it.
