### ISSUE TITLE
Doesn't rotate on iPad

### ISSUE THREAD

**Issue by Doneyy** [theQRL/mobile-wallet#20]
General: Doesn’t seem to rotate on iPad. (Like if you turn your iPad from vertical to horizontal, it doesn’t move with the screen.)
Ipad version ME279NF/A
iOS Version 12.1.1 (16C50)

**Comment by ademcan** [comment]
I have added the ability to rotate the app on the iPad. However, I realized that some of the views are not adapted to the iPad's format (I didn't try it earlier on iPad). This is definitely something I'll check in details, probably for the next release.
