### ISSUE TITLE
"Add pin" Is confusing imo

### ISSUE THREAD

**Issue by Doneyy** [theQRL/mobile-wallet#21]
- Starting the app: creating the first wallet. Add pin: Maybe more clear to say something like Create 4-number password/ Pin (Found it confusing the way it's stated now.)
Ipad version ME279NF/A
iOS Version 12.1.1 (16C50)

**Comment by ademcan** [comment]
I agree "ADD PIN" was not very clear. I changed it to "CREATE 4-DIGIT PIN", will be updated in the next version, thanks 👍
