### ISSUE TITLE
“This may take a while” Is half visible.

### ISSUE THREAD

**Issue by Doneyy** [theQRL/mobile-wallet#22]
- Starting the app: creating the first wallet. After adding pin, and pressed create wallet the text “This may take a while” Is half visible. Like in the horizontal way  I see all letters, but only the top half.
Ipad version ME279NF/A
iOS Version 12.1.1 (16C50)

**Comment by ademcan** [comment]
This issue is now solved. Once the user clicks "Create Wallet", the 2 buttons disappear and the text "This may take a while. Please be patient..." with a loading spinner is shown instead.
