### ISSUE TITLE
Keyboard stays in view and the “review” button is hidden behind the keyboard.

### ISSUE THREAD

**Issue by Doneyy** [theQRL/mobile-wallet#23]
- On the page “send and receive”. When sending QRL, if the recipient and the amount is typed, the keyboard stays and the “review” button is hidden behind the keyboard. Either it should disappear when I tap above the keyboard, or there should be a button that can hide the keyboard. Now I need to tap on receive, to leave the send page, and then again go back to the send page to be able to send the transaction. 
Ipad version ME279NF/A
iOS Version 12.1.1 (16C50)

**Comment by ademcan** [comment]
This issue is now solved, the keyboard is hidden once the user presses anywhere on the screen.
