### ISSUE TITLE
Back up your wallet could use a "copy" button

### ISSUE THREAD

**Issue by Doneyy** [theQRL/mobile-wallet#26]
- On the page “Back up your wallet”. Opening this, shows the Mnemonic and the Hexeed. It would be nice to add the “copy” button as you have on the “Receive” page where I can copy my address. Also maybe add some info about this for users who are new to crypto. Like an “i” button for information and recommendations how to safe and where to safe the backup.
Ipad version ME279NF/A
iOS Version 12.1.1 (16C50)

**Comment by ademcan** [comment]
Hi Doneyy, thank you for your comment. I understand what you mean by the copy button on the "Back up your wallet" view. However, I am wondering how useful would that be. 
Do you really need to copy/access your hexseed or mnemonic on the wallet app? 

The "i" (information) icon is a good idea, will add that.

**Comment by Doneyy** [comment]
I thought you could copy paste to your mail and safe it on a memorystick as backup, or print it as a backup? Not sure how else you would back up your wallet. But then again maybe next time, the "i" icon will clarify that for me. ;)

**Comment by ademcan** [comment]
I agree, it indeed makes sense :) This is how I implemented it (coming in the next PR):
- user clicks the "View" button
- a modal window with 2 buttons (Cancel and Show) appears and reminds the user to be careful 
- user clicks "Cancel" to cancel or "Show" to see the mnemonic and hexseed
I also made the mnemonic and hexseed copiable by pressing and holding.

**Comment by Doneyy** [comment]
Sounds great!
