### ISSUE TITLE
List of existing wallets

### ISSUE THREAD

**Issue by Doneyy** [theQRL/mobile-wallet#30]
- On the page "Create new wallet”. I would not expect to find my list of existing wallets there. That is confusing. (Maybe name that tab “Wallets” or something.) Also: first I thought it was just an oversight where I could remove wallets. I tapped on the address and nothing happened. Then later I noticed I had to tap the red icon to open the wallet. Maybe make it so that, besides typing on the icon, if you tap the address, it will open the “enter pin” screen.
Ipad version ME279NF/A
iOS Version 12.1.1 (16C50)

**Comment by ademcan** [comment]
Hi Doneyy, thank you for your comment.
This issue is now solved, see PR31 https://github.com/theQRL/mobile-wallet/pull/31 that brings the following changes:
- Change "Create new wallet" to "Wallets" on the side menu
- User can now switch to a wallet by touching its name (not only the wallet icon)
