### ISSUE TITLE
OTS Key index begin with 8

### ISSUE THREAD

**Issue by 0xFF0** [theQRL/mobile-wallet#34]
**Action**: Click on Send & Receive
**What happened**: OTS key is incorrect. OTS Key index should be 0 (when there's no transaction) but wallet display 8.
**Android/iOS version**: 7.1.2
**Android/iOS handset model:** NoxPlayer 6.2.6.1 (Galaxy Note 3 emulation).

![ots](https://user-images.githubusercontent.com/42574567/51009061-8cfa6b00-151c-11e9-9f7c-13ff548502f6.png)

**Comment by jplomas** [comment]
We're not aware of OTS index issues as implemented with the launch version.  Granular control of OTS keys for advanced users is in the future roadmap.
