### ISSUE TITLE
App crash after pressing quit button on password failed attempt page

### ISSUE THREAD

**Issue by 12remember** [theQRL/mobile-wallet#72]
Action: After 3 failed password attempts > getting screen with the timer > pressing button quit 

Expected Result:  Getting back to mainscreen (Balance page)

Actual Result: App crashes  with the error "Qrl Wallet has been stopped"

Android Version: 7.0
Android Handset model: Samsung Galaxy S6  SM-G920F

**Comment by ademcan** [comment]
Thanks, this issue has been solved in v2.0.7.
The "Quit" button has been removed as its action is not supported as is on React Native. Users can quit the app using the default action based on their operating system.
